updating

diff --git a/roles/firstboot/tasks/RedHat.yml b/roles/firstboot/tasks/RedHat.yml
--- a/roles/firstboot/tasks/RedHat.yml
+++ b/roles/firstboot/tasks/RedHat.yml
@@ -334,189 +334,189 @@
       - '.firstboot'
       - '.bootstrap'
 
-- name: entitlement block
-  block:
-    - name: "Fall back to RHSM, Check if we are registered"
-      shell: "subscription-manager status"
-      register: rhsm_reg
-      become: yes
-  when:
-  - firstbootcheck.stdout == "false"
-
-  rescue: 
-    - name: "Bootstrap check"
-      shell: |
-        if [ -e "/opt/.bootstrap" ]
-        then
-          echo "true"
-        else
-          echo "false"
-        fi
-      register: bootstrapcheck
-    
-    - name: "Try to register to Satellite 6"
-      block:
-        - name: "Get the bootstrap python script"
-          get_url:
-            url: "http://{{ sat6_fqdn }}/pub/bootstrap.py"
-            dest: /opt/bootstrap.py
-            mode: 0755
-          become: true
-
-        - name: "Save the command to register to satellite server"
-          template:
-            src: reg-to-satellite.sh.j2
-            dest: /opt/reg-to-satellite.sh
-            owner: root
-            group: root
-            mode: 0755
-          become: true
-          when:
-          - sat6_fqdn != "None"
-
-#    - name: "Fixing python for rhel 8"
-#      shell: "alternatives --config python"
-#      become: true
-#      args:
-#        creates: /opt/.firstboot
+#- name: entitlement block
+#  block:
+#    - name: "Fall back to RHSM, Check if we are registered"
+#      shell: "subscription-manager status"
+#      register: rhsm_reg
+#      become: yes
+#  when:
+#  - firstbootcheck.stdout == "false"
+#
+#  rescue: 
+#    - name: "Bootstrap check"
+#      shell: |
+#        if [ -e "/opt/.bootstrap" ]
+#        then
+#          echo "true"
+#        else
+#          echo "false"
+#        fi
+#      register: bootstrapcheck
+#    
+#    - name: "Try to register to Satellite 6"
+#      block:
+#        - name: "Get the bootstrap python script"
+#          get_url:
+#            url: "http://{{ sat6_fqdn }}/pub/bootstrap.py"
+#            dest: /opt/bootstrap.py
+#            mode: 0755
+#          become: true
+#
+#        - name: "Save the command to register to satellite server"
+#          template:
+#            src: reg-to-satellite.sh.j2
+#            dest: /opt/reg-to-satellite.sh
+#            owner: root
+#            group: root
+#            mode: 0755
+#          become: true
+#          when:
+#          - sat6_fqdn != "None"
+#
+##    - name: "Fixing python for rhel 8"
+##      shell: "alternatives --config python"
+##      become: true
+##      args:
+##        creates: /opt/.firstboot
+##      when:
+##      - ansible_distribution_major_version == '8'
+#        
+#        - name: "Run the satellite bootstrap script"
+#          shell: |
+#            /opt/reg-to-satellite.sh
+#            #/bin/false
+#          become: true
+#          register: satbootstrap
+#          #when: "'Current' not in rhsm_reg.stdout"
+#          when:
+#          - bootstrapcheck.stdout == "false"
+#          - sat6_fqdn != "None"
+#
+#        - name: "bootstrap complete"
+#          file:
+#            path: /opt/.bootstrap
+#            state: touch
+#            mode: 0444
+#          become: true
+#          when:
+#          - sat6_fqdn != "None"
 #      when:
-#      - ansible_distribution_major_version == '8'
-        
-        - name: "Run the satellite bootstrap script"
-          shell: |
-            /opt/reg-to-satellite.sh
-            #/bin/false
-          become: true
-          register: satbootstrap
-          #when: "'Current' not in rhsm_reg.stdout"
-          when:
-          - bootstrapcheck.stdout == "false"
-          - sat6_fqdn != "None"
-
-        - name: "bootstrap complete"
-          file:
-            path: /opt/.bootstrap
-            state: touch
-            mode: 0444
-          become: true
-          when:
-          - sat6_fqdn != "None"
-      when:
-      - bootstrapcheck.stdout == "false"
-      #- sat6_fqdn != "None"
-    
-      rescue:
-        - name: "Clean up from Sat 6"
-          shell: |
-            subscription-manager remove --all
-            subscription-manager clean
-            [ -e /etc/rhsm/rhsm.conf.kat-backup ] && cp -f /etc/rhsm/rhsm.conf.kat-backup /etc/rhsm/rhsm.conf
-          become: true
-          ignore_errors: true
-      
-      #    - name: Register and subscribe to multiple pools for virtual hosts
-      #      community.general.redhat_subscription:
-      #        state: present
-      #        username: "{{ rh_satellite_user }}"
-      #        password: "{{ rh_satellite_pass }}"
-      #        pool_ids: "{{ rh_subscription_pool_ids }}"
-      #    #    pools: "{{ rh_subscription_pools }}"
-      #      become: true
-      #      register: rhsm_status
-      #      #when: "'Current' not in rhsm_reg.stdout"
-      #      #when: "'Current' not in rhsm_reg.stdout and ansible_virtualization_role == 'guest' "
-      #      retries: 3
-      #      until: rhsm_status.msg.find("System successfully registered") != -1
-      #      delay: 1
-
-        - name: "subscribe to the cdn"
-          shell: subscription-manager register --auto-attach --username "{{ rh_satellite_user }}" --password "{{ rh_satellite_pass }}"
-          become: yes
-
-        - name: "bootstrap complete"
-          file:
-            path: /opt/.bootstrap
-            state: touch
-            mode: 0444
-          become: true
-      always:
-        - name: "Disabling all repos"
-          shell: "subscription-manager repos --disable={{ item }}"
-          with_items: "{{ rh_disabled_repos }}"
-          become: true
-          args:
-            creates: /opt/.firstboot
-          when:
-          - ansible_distribution_major_version == '7'
-        
-        - name: "Enabling needed repos for rhel7"
-          shell: "subscription-manager repos --enable={{ item }}"
-          with_items: "{{ rh7_enabled_repos }}"
-          become: true
-          args:
-            creates: /opt/.firstboot
-          when:
-          - ansible_distribution_major_version == '7'
-        
-        - name: "Installing base config rpms"
-          yum:
-            name: "{{ redhat_packages }}"
-            state: latest
-          become: true
-          when:
-          - ansible_distribution_major_version == '7'
-
-        - name: "Adding python2, pip and python expect for RHEL7"
-          shell: |
-            rpm -qa | grep epel || rpm -ivh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
-            yum-config-manager --disable epel
-            yum -y install --enablerepo=epel python2-pip
-            pip install --upgrade pexpect
-          become: true
-          ignore_errors: yes
-          args:
-            creates: /opt/.firstboot
-          when:
-          - ansible_distribution_major_version == '7'
-
-        - name: "Installing base config rpms"
-          yum:
-            name: "{{ redhat8_packages }}"
-            state: latest
-          become: true
-          when:
-          - ansible_distribution_major_version == '8'
-
-      #    - name: "Update dns entry"
-      #      shell: "/sbin/ifup-local || true"
-      #      become: true
-      #      ignore_errors: yes
-      #      args:
-      #        creates: /opt/.firstboot
-
-        - name: "Disable firewall"
-          service:
-            name: "firewalld"
-            state: "stopped"
-            enabled: no
-          become: true
-
-      #    - name: "Reboot."
-      #      shell: |
-      #        shutdown -r +1 || true
-      #      become: true
-      #      args:
-      #        executable: /bin/bash
-      #        creates: /opt/.firstboot
-      #
-      #    - name: "Wait 5 to 11 mins for host to reboot"
-      #      wait_for:
-      #        port: 22
-      #        host: "{{ ansible_ssh_host | default(inventory_hostname) }}"
-      #        #search_regex: OpenSSH
-      #        delay: 60
-      #        timeout: 660
-      #      delegate_to: localhost
-      #      become: false
-  when:
-    - firstbootcheck.stdout == "false"
+#      - bootstrapcheck.stdout == "false"
+#      #- sat6_fqdn != "None"
+#    
+#      rescue:
+#        - name: "Clean up from Sat 6"
+#          shell: |
+#            subscription-manager remove --all
+#            subscription-manager clean
+#            [ -e /etc/rhsm/rhsm.conf.kat-backup ] && cp -f /etc/rhsm/rhsm.conf.kat-backup /etc/rhsm/rhsm.conf
+#          become: true
+#          ignore_errors: true
+#      
+#      #    - name: Register and subscribe to multiple pools for virtual hosts
+#      #      community.general.redhat_subscription:
+#      #        state: present
+#      #        username: "{{ rh_satellite_user }}"
+#      #        password: "{{ rh_satellite_pass }}"
+#      #        pool_ids: "{{ rh_subscription_pool_ids }}"
+#      #    #    pools: "{{ rh_subscription_pools }}"
+#      #      become: true
+#      #      register: rhsm_status
+#      #      #when: "'Current' not in rhsm_reg.stdout"
+#      #      #when: "'Current' not in rhsm_reg.stdout and ansible_virtualization_role == 'guest' "
+#      #      retries: 3
+#      #      until: rhsm_status.msg.find("System successfully registered") != -1
+#      #      delay: 1
+#
+#        - name: "subscribe to the cdn"
+#          shell: subscription-manager register --auto-attach --username "{{ rh_satellite_user }}" --password "{{ rh_satellite_pass }}"
+#          become: yes
+#
+#        - name: "bootstrap complete"
+#          file:
+#            path: /opt/.bootstrap
+#            state: touch
+#            mode: 0444
+#          become: true
+#      always:
+#        - name: "Disabling all repos"
+#          shell: "subscription-manager repos --disable={{ item }}"
+#          with_items: "{{ rh_disabled_repos }}"
+#          become: true
+#          args:
+#            creates: /opt/.firstboot
+#          when:
+#          - ansible_distribution_major_version == '7'
+#        
+#        - name: "Enabling needed repos for rhel7"
+#          shell: "subscription-manager repos --enable={{ item }}"
+#          with_items: "{{ rh7_enabled_repos }}"
+#          become: true
+#          args:
+#            creates: /opt/.firstboot
+#          when:
+#          - ansible_distribution_major_version == '7'
+#        
+#        - name: "Installing base config rpms"
+#          yum:
+#            name: "{{ redhat_packages }}"
+#            state: latest
+#          become: true
+#          when:
+#          - ansible_distribution_major_version == '7'
+#
+#        - name: "Adding python2, pip and python expect for RHEL7"
+#          shell: |
+#            rpm -qa | grep epel || rpm -ivh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
+#            yum-config-manager --disable epel
+#            yum -y install --enablerepo=epel python2-pip
+#            pip install --upgrade pexpect
+#          become: true
+#          ignore_errors: yes
+#          args:
+#            creates: /opt/.firstboot
+#          when:
+#          - ansible_distribution_major_version == '7'
+#
+#        - name: "Installing base config rpms"
+#          yum:
+#            name: "{{ redhat8_packages }}"
+#            state: latest
+#          become: true
+#          when:
+#          - ansible_distribution_major_version == '8'
+#
+#      #    - name: "Update dns entry"
+#      #      shell: "/sbin/ifup-local || true"
+#      #      become: true
+#      #      ignore_errors: yes
+#      #      args:
+#      #        creates: /opt/.firstboot
+#
+#        - name: "Disable firewall"
+#          service:
+#            name: "firewalld"
+#            state: "stopped"
+#            enabled: no
+#          become: true
+#
+#      #    - name: "Reboot."
+#      #      shell: |
+#      #        shutdown -r +1 || true
+#      #      become: true
+#      #      args:
+#      #        executable: /bin/bash
+#      #        creates: /opt/.firstboot
+#      #
+#      #    - name: "Wait 5 to 11 mins for host to reboot"
+#      #      wait_for:
+#      #        port: 22
+#      #        host: "{{ ansible_ssh_host | default(inventory_hostname) }}"
+#      #        #search_regex: OpenSSH
+#      #        delay: 60
+#      #        timeout: 660
+#      #      delegate_to: localhost
+#      #      become: false
+#  when:
+#    - firstbootcheck.stdout == "false"
